name: Build and Release Expo App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npm install -g expo-cli
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0-<LaTex>${{ github.run_number }}
          name: DizzAí iOS v1.0.0 Build $</LaTex>{{ github.run_number }}
          body: "🚀 DizzAí iOS - Build automático!"
          draft: false
